version: '3'

volumes:
  wp_volume:
   driver: local
   driver_opts:
    o: bind
    type: volume
    device: /home/bbaudry/data/wp_inception

services:
 wordpress:
  container_name: wordpress
  build:
   context: ./requirements/wordpress
   dockerfile: Dockerfile
  volumes:
   - wp_volume:/var/www/
  ports:
   - "9000:9000"
  working_dir: /var/www/
  networks:
   - network

 nginx:
  container_name: nginx
  depends_on:
   - wordpress
  build:
   context: ./requirements/nginx
   dockerfile: Dockerfile
  volumes:
   - wp_volume:/var/www/
  ports:
   - "443:443"
  networks:
   - network

networks:
 network:
   name: inception
